### ISSUE TITLE
[Questions] Using eio to build an application

### ISSUE THREAD

**Issue by sidkshatriya** [ocaml-multicore/eio#105]
I'm looking forward to the prospect of writing monad-less effects in OCaml. So this library is exciting to me. Thanks for your work on it!

Right now I'm looking to make a single domain application, possibly with Eio. I am aware the Eio is very much a work-in-progress and experimental.

I recently notice https://github.com/ocaml-multicore/ocaml-multicore/issues/770 -- I didn't go deep into the issue but it seems that this is related to domains + effects and since I'm considering only a single domain application it does not impact my use case. Though it's heartening to know that a fix for this was found and promptly applied to the 5.00 multicore branch. 

But the questions I have are:
- As you find bugs in multicore while working on Eio, the fixes will be only on the ocaml-multicore 5.00 branch (which is confusingly called 4.14+domains in the opam file). However, Eio is currently built to run on 4.12+domains. How will that work out? Is there a plan to have a Eio for 4.14+domains ?
- The tooling support in 4.14 in general and 4.14+domains in particular is/will be quite poor in the immediate term, so even if you _did_ shift to using Eio on 4.14+domains the development experience would be quite difficult. For instance merlin would not work on 4.14 / 4.14+domains for quite some time. Also the 5.00 (aka 4.14+domains) seems to not compiling too many packages compared to 4.12+domains (according to http://check.ocamllabs.io:8082/ )

I know all these questions relate to this transitional period and things will sort themselves out eventually. But this transition is likely to take many months so I'm wondering if you have any recommendations on what might be the best strategy if I want to use Eio right now.

(Thanks for your time!)

**Comment by talex5** [comment]
This is a good point. I asked @kayceesrk and he says he'll backport the fix to 4.12. As long as you don't use domains you shouldn't hit this problem though.

Having people try out Eio for various things would be very useful, but you'll have to be prepared to add things you need that are missing and update your code as the APIs change.

**Comment by kayceesrk** [comment]
See https://github.com/ocaml-multicore/ocaml-multicore/pull/781.

**Comment by sidkshatriya** [comment]
@kayceesrk Thank you! 

Since we're on the subject, do you think there are any more fixes that might need to be backported from the 5.00 branch to the 4.12+domains branch?

I also have another question: there are a lot of failures on 5.00 (i.e. 4.14+domains) at http://check.ocamllabs.io:8082/ unlike 4.12+domains. I realize its just transitional but when can we have 4.12+domain levels of passing? Is this breakage because of ppx/similar tools failing to work with 4.14+domains or something due to multicore itself?

Ideally we can just work on the 5.00 (4.14+domains) as 4.12+domains seems to be quite old by now and not getting all the updates that the 5.00 branch is regularly...

Or is 4.12+domains still the way to go for now for things like `eio` ?

**Comment by kayceesrk** [comment]
> Since we're on the subject, do you think there are any more fixes that might need to be backported from the 5.00 branch to the 4.12+domains branch?

4.12+domains branch is not actively maintained. Given the laundry list of tasks to get to 5.00, the multicore team just does not have the resource to backport all the changes to older versions. This particular change was backported to allow us to continue to experiment with `eio`. This is not the norm.

The CI failures are expected as many packages do not work with unreleased versions. The column to compare is not 4.12+domains but `trunk`. The failures on `5.00` branch (multicore) are the same as those on `trunk` (modulo a few outliers).
