### ISSUE TITLE
Decide how to represent pathnames

### ISSUE THREAD

**Issue by talex5** [ocaml-multicore/eio#124]
At the moment, paths in Eio are strings, which are used in the context of some base directory. e.g.

```ocaml
Eio.Dir.with_open_in cwd "foo/input.dat" (fun flow -> ...)
```

This should work well on most systems, but we need to think about how to support Windows too.

Possibilities include:

- Using Unix path strings everywhere and providing a way to import and export Windows paths.
- Using an abstract type for paths.

The [Fpath](https://erratique.ch/software/fpath) library encodes lots of knowledge about Windows paths. It probably can't be used directly because its paths behave differently depending on the host platform (preventing e.g. a program running on Linux from creating paths that are to be used on Windows). The path rules should probably be per-filesystem instead.

- [ ] Find out what other languages do (e.g. look at [Python's pathlib](https://docs.python.org/3/library/pathlib.html), Rust, etc).

**Comment by samwgoldman** [comment]
My 2¢ here is to leave paths as strings. Getting paths "right" for all use cases doesn't seem possible, and having a flexible low-level API somewhere, even if it opens up the possibility for errors, seems valuable to me.

For Flow, we have the need to share paths between platforms. These are relative paths, using the `/` path separator. We only support Windows systems that transparently support the `/` path separator, so we can just pass these paths into Windows APIs without transforming them.

However, we do build wrappers around the various paths, to ensure they are not mishandled. But this is an application-layer concern for us. We take the strings returned by system calls into the appropriate (unboxed) wrapper type and coerce back into strings as needed.

**Comment by talex5** [comment]
Thanks, that makes sense. And I see that DOS has always supported `/` as a path separator anyway:

https://learn.microsoft.com/en-us/archive/blogs/larryosterman/why-is-the-dos-path-character

**Comment by avsm** [comment]
Do you have a link to your path wrapper library, @samwgoldman?  It'd be interesting to contrast it with Fpath and Python's Pathlib. I agree that keeping strings at a low-level in Eio is a reasonable for Eio 1.0.
