### ISSUE TITLE
API for spawning sub-processes

### ISSUE THREAD

**Issue by talex5** [ocaml-multicore/eio#126]
Eio needs to provide a way to create and manage sub-processes (like `Lwt_process`).

- Must work in programs using multiple domains. Note that `Unix.fork` cannot be used there.
- API should try to prevent bugs with argument splitting (e.g. avoid error-prone `Unix.system` style API by default). But also needs to work on Windows, where I think you can't provide an argv.
- Child processes should be attached to a switch by default to avoid leaking them, but need a way to spawn detached sub-processes too.
- Must allow passing pipes, etc, to child processes.
- Must prevent accidentally leaking FDs to child processes. All FDs in Eio are already opened with close-on-exec set for this reason.
- Should provide a simple way to check or report the process's exit status.

Possible sources of inspiration include:

- [Lwt_process](http://ocsigen.org/lwt/5.2.0/api/Lwt_process)
- [Bos.Cmd](https://erratique.ch/software/bos/doc/Bos/Cmd/index.html)
- [Feather](https://github.com/charlesetc/feather)
- [Python's subprocess](https://docs.python.org/3/library/subprocess.html#module-subprocess)

Current status:

- [x] #359
- [x] #461
- [x] #464 
- [x] #472
- [ ] #473

**Comment by patricoferris** [comment]
Just a heads up that I've started looking into this as I'm going to need it for some applications I'm building. Hopefully will have a draft PR in the next week or two to iron out the details :))

**Comment by benmandrew** [comment]
Polite bump; this would be extremely useful for converting a lot of the ocurrent ecosystem to Eio. The work in https://github.com/ocurrent/obuilder/pull/113 looks great so far!

**Comment by talex5** [comment]
The current PR (submitted 2 days ago) is here: https://github.com/ocaml-multicore/eio/pull/473

**Comment by talex5** [comment]
Implemented in #499.
