### ISSUE TITLE
Switches and background tasks

### ISSUE THREAD

**Issue by SquidDev** [ocaml-multicore/eio#148]
I'm currently fiddling with building a DBus library on top of libsystemd and eio. Really enjoying using eio, though I did have some questions about how best to design the API to fit within eio's model.

The main problem at hand is that one needs to run a background task which waits for the underlying socket to become readable/writable and then gets libsystemd to process its message queue[^1]. I originally had something like this:

```ocaml
let rec process bus = 
  await_event bus;
  sd_bus_process bus;
  process bus

let rec create ~sw () = 
  let bus = (* ... *) in
  Fibre.fork ~sw (fun () -> process bus);
  Switch.on_release sw (fun () -> sd_bus_close bus);
  bus
```

This obviously doesn't quite do what you want though, as the `process` fibre keeps the switch open forever.

I've had a quick look at how other structured concurrency libraries handle the problem of background tasks which shouldn't keep the switch open, but haven't had much luck (I realise in most cases it is pretty undesirable). Is there anything obvious in eio I'm missing, or is my best option just to provide an explicit `close` method which shuts down this task?

**Comment by talex5** [comment]
The easiest way is to raise an exception at the end of the main function. Lwt_eio does that to kill off its background threads:

https://github.com/talex5/lwt_eio/blob/af14d52228fe6b030e1aec1abfdd26cdebb0e741/lib/lwt_eio.ml#L87

The slight annoyance is that the switch then raises the exception, which you have to ignore. I'm tempted to add a `Switch.cancel` to cancel any attached fibres, but without causing the switch itself to fail.

**Comment by SquidDev** [comment]
Oh, that makes sense. It's definitely not perfect, but I guess I can build a wrapper which hides the internals.

Thank you very much!
