### ISSUE TITLE
Consider renaming `Fibre.fork`

### ISSUE THREAD

**Issue by talex5** [ocaml-multicore/eio#196]
As mentioned on discuss, this name isn't very helpful:

- It's unrelated to `Unix.fork`, which can be confusing.
- Since adding the switch argument, it doesn't actually copy the calling environment at all.

Should probably be renamed to `create`, `start`, `spawn`, or something like that.

**Comment by avsm** [comment]
We need to also rename the various other `fork_*` functions (`fork_sub`, `fork_daemon`, `fork_promise`) if we do this.

**Comment by talex5** [comment]
Since adding fiber-local storage, it is now forking the environment again. I think the current name is OK, so closing.
