### ISSUE TITLE
Stuck on networking echo service

### ISSUE THREAD

**Issue by impvd** [ocaml-multicore/eio#233]
I'm trying to extend the example of [Networking](https://github.com/ocaml-multicore/eio#networking) to a client-server echo service, as we learned from network programming course 101.

And here's my code:

```
open Eio.Std

let run_client ~net ~addr =
  traceln "Connecting to server...";
  Switch.run @@ fun sw ->
  let flow = Eio.Net.connect ~sw net addr in
  Eio.Flow.copy_string "Hello from client" flow;
  let b = Buffer.create 100 in
  Eio.Flow.copy flow (Eio.Flow.buffer_sink b);
  traceln "Client received : %S from server" (Buffer.contents b);
  ;;  

let run_server socket =
  Switch.run @@ fun sw ->
  Eio.Net.accept_sub socket ~sw (fun ~sw flow _addr ->
    traceln "Server accepted connection from client";
    let b = Buffer.create 100 in
    Eio.Flow.copy flow (Eio.Flow.buffer_sink b);
    traceln "Server received: %S" (Buffer.contents b);
    Eio.Flow.copy_string (Buffer.contents b) flow;
    traceln "Server echo: %S to client" (Buffer.contents b);
  ) ~on_error:(traceln "Error handling connection: %a" Fmt.exn);
  traceln "(normally we'd loop and accept more connections here)"
  ;;

  let main ~net ~addr =
    Switch.run @@ fun sw ->
    let server = Eio.Net.listen net ~sw ~reuse_addr:true ~backlog:5 addr in
    traceln "Server ready...";
    Fiber.both
      (fun () -> run_server server)
      (fun () -> run_client ~net ~addr)
  ;;
```

However, it got stuck as below:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/37371804/175492132-6919d449-cac6-4089-ba1a-65ad7470baad.png">

Just wondering if anything I'd missed?

**Comment by talex5** [comment]
The server is waiting until it has received all the data from the client, and the client is waiting to receive data from the server.

Either the client needs to tell the server it's done (``Flow.shutdown flow `Send``), or the server needs to stop reading before the end (e.g. using `Buf_read.line` to stop after one line).
