### ISSUE TITLE
Expose `unix_fd` in `Eio.Net.accept{,_fork}`

### ISSUE THREAD

**Issue by anmonteiro** [ocaml-multicore/eio#286]
I've found myself needing to access the underlying file descriptor for a server that calls `Eio.Net.accept{,_fork`, but the socket is only exposed as a `Flow.two_way`.

My use case is the `sendfile` syscall.

**Comment by talex5** [comment]
`Eio_unix.FD.peek` should do it, though perhaps we should just make `Flow.copy` use `sendfile` automatically when the source is a regular file.

**Comment by anmonteiro** [comment]
I can try it later but I was under the impression the types wouldn’t work out, e.g. calling peek on something that isn’t a `<unix_fd>`

**Comment by talex5** [comment]
Sorry, I meant [Eio_unix.FD.peek_opt](https://ocaml-multicore.github.io/eio/eio/Eio_unix/FD/index.html#val-peek_opt). That will check at runtime whether an FD is available.

**Comment by anmonteiro** [comment]
oh, that's a `Generic.t -> Unix.file_descr option`. I had missed it, sorry about that.
