### ISSUE TITLE
Implement signature that expects covariant type parameter

### ISSUE THREAD

**Issue by anmonteiro** [ocaml-multicore/eio#297]
Most signatures that abstract over Lwt / Async currently define an interface to be implemented by the I/O runtime.

Part of that interface is usually:

```ocaml
type +'a t
```

I took a stab at implementing one of these (Caqti, in particular) for my own use, and I was trying to use an `Eio.Promise.t` (which is itself defined as `type !'a t`). The OCaml compiler doesn't seem to like it:

```
Error: In this definition, expected parameter variances are not satisfied.
       The 1st type parameter was expected to be covariant,
       but it is injective invariant.
```

Do you have a recommended solution? Is my only hope to implement a wrapper of sorts, or alternatively can the type parameter for Eio.Promise.t be made covariant?

**Comment by talex5** [comment]
It can be done using `Obj.magic` internally (which is what Lwt does: https://github.com/ocsigen/lwt/blob/01eb4583f1f3a782351621248c7cb705056fb63e/src/core/lwt.ml#L546).

I think this is a reasonable change to make. Do you want to submit a PR?

**Comment by anmonteiro** [comment]
I opened an initial draft in https://github.com/ocaml-multicore/eio/pull/300
