### ISSUE TITLE
What to do for `ftruncate`?

### ISSUE THREAD

**Issue by nojb** [ocaml-multicore/eio#305]
Is this function missing from `eio`, or is one supposed to use the one in the `unix` library (via `eio_unix`)?

**Comment by nojb** [comment]
Also: "seek".

**Comment by talex5** [comment]
There are lots of missing functions - PRs welcome!

**Comment by talex5** [comment]
`seek` and `truncate` were added in https://github.com/ocaml-multicore/eio/pull/626.
