### ISSUE TITLE
Eio.Path.load loads only first 4gb on big files

### ISSUE THREAD

**Issue by EduardoRFS** [ocaml-multicore/eio#335]
I'm using the Luv backend and when trying to load a file bigger than 4gb's the result string always ends up being the first 4gb's of the file.

**Comment by haesbaert** [comment]
Can confirm:
```
$ dune build && EIO_BACKEND=luv ./_build/default/bench/foo.exe
len=4294967296
[0]=A
[2^32 - 1]=A
Fatal error: exception Invalid_argument("index out of bounds")

$ ./_build/default/bench/foo.exe
len=4294967297
[0]=A
[2^32 - 1]=A
[2^32]=B
```

My first suspicion was not using 64bits off_t, but it seems it is, at some point someone is storing it in 32bit.

**Comment by haesbaert** [comment]
The bug seems to be internal to libuv:
```
uv_fs_read:2006
uv__fs_read:473
uv__fs_read:481 result=2147479552 len=2147483648
+got = 2147479552
uv_fs_read:2006
uv__fs_read:473
uv__fs_read:481 result=4096 len=4096
+got = 4096
uv_fs_read:2006
uv__fs_read:473
uv__fs_read:481 result=0 len=0  <--- here libuv is calling read(2) with a buffer of zero length, so it returns 0.
```

**Comment by haesbaert** [comment]
We're actually passing a 2^32 buffer, somehow it turns into 0, somewhere must be wrapping around, anyway it's late.
```
uv_fs_read:2006
uv__fs_read:473
uv__fs_read:481 result=4096 len=4096
+got = 4096
+our cstruct len=4294967296 balen=4294967296
uv_fs_read:2006
uv__fs_read:473
uv__fs_read:481 result=0 len=0
+>>EOF<<
```

**Comment by haesbaert** [comment]
So the bug seems to be in luv, we pass the correct number, but libuv gets an very likely overflowed int.
I need to learn ctypes to continue.

**Comment by haesbaert** [comment]
Found it:
https://github.com/aantron/luv/blob/0ed668e87ca55d65f4f84422b0dd3381701c71b0/src/helpers.ml#L53

```
utop # Unsigned.UInt.of_int 4294967296;;
- : Unsigned.uint = <uint 0>
```

**Comment by anmonteiro** [comment]
It might be time to start discussing a community fork of luv if we ever want to see that fixed.

**Comment by haesbaert** [comment]
> It might be time to start discussing a community fork of luv if we ever want to see that fixed.

Yes, we also have an unstable ABI with uring (I've hit two kernel bugs the last week). I also don't think luv offers much, there had been talks about just writing a pure backend that is at least POSIX and windows can eat cake.

**Comment by talex5** [comment]
We can work around this in eio_luv quite easily by limiting the amount we ask libuv to read in one go to 2GB. It's unlikely it would do more than that anyway, and the caller will handle it like any other short read.

**Comment by haesbaert** [comment]
> We can work around this in eio_luv quite easily by limiting the amount we ask libuv to read in one go to 2GB. It's unlikely it would do more than that anyway, and the caller will handle it like any other short read.

It's done here: https://github.com/ocaml-multicore/eio/pull/339/commits/e2f38d35493f961d3efdc05f37a5a131a0e5fd03, needs some ironing out and maybe I should pull that out of that PR.

**Comment by talex5** [comment]
A separate PR would be great!
