### ISSUE TITLE
datagram_socket t#recv does not return on empty packet

### ISSUE THREAD

**Issue by cdaringe** [ocaml-multicore/eio#340]
# problem

⚠️ mediocre code ahead (ref: https://github.com/cdaringe/protohacks/blob/c4e00f6f55b991d780d46f012a460bb8a528c505/lib/server/server.ml#L33-L44)

```ml
      let client_addr, r = recv socket buf in
      traceln "ack";
```

`ack` is never emitted when empty packets are sent. yes, `ack` is objectively the wrong debug word in this scenario 😆 

<img width="797" alt="image" src="https://user-images.githubusercontent.com/1003261/194503484-c41507f4-4c70-49c2-a04a-4ed0c7e949d1.png">

i'm using linux in docker, so perhaps something with the libuv bindings? in the wireshark snippet above, you can see the service retrying, hoping i'll send them a response, but sure enough, the first time they send me an empty packet, i'm unable to proceed passed `recv`

**Comment by haesbaert** [comment]
hmm I can't reproduce, maybe I'm missing something:
```ocaml
let traceln = Eio.traceln

let server_addr = `Udp (Eio.Net.Ipaddr.V4.any, 18018)
let client_addr = `Udp (Eio.Net.Ipaddr.V4.any, 18019)

let reader env () =
  Eio.Switch.run @@ fun sw ->
  let socket = Eio.Net.datagram_socket ~sw (Eio.Stdenv.net env) server_addr in
  let buf = Cstruct.create 64 in
  let _, r = Eio.Net.recv socket buf in
  traceln "Got %d bytes" r;
  Eio.Net.close socket

let sender env () =
  Eio.Switch.run @@ fun sw ->
  let socket = Eio.Net.datagram_socket ~sw (Eio.Stdenv.net env) client_addr in
  let buf = Cstruct.create 0 in
  Eio.Net.send socket server_addr buf;
  traceln "Sent %d bytes" (Cstruct.length buf);
  Eio.Net.close socket

let () =
  Eio_main.run @@ fun env ->
  Eio.Fiber.both (reader env) (sender env)
```

```
sam:eio: dune build && ./_build/default/bench/foo.exe
+Sent 0 bytes
+Got 0 bytes
sam:eio: dune build && EIO_BACKEND=luv ./_build/default/bench/foo.exe
+Sent 0 bytes
+Got 0 bytes
```

**Comment by cdaringe** [comment]
indeed, your repro is solid. i split your reader/writer between independent processes, and it still succeeded.

thanks for your time, sorry for not providing such a reproduction on init.

it seems that i have issue getting empty packets from osx into docker. 1 byte packets make it thru, but 0 len packets aren't getting through :|. yarg!

**Comment by haesbaert** [comment]
> indeed, your repro is solid. i split your reader/writer between independent processes, and it still succeeded.
> 
> thanks for your time, sorry for not providing such a reproduction on init of the issue.
> 
> it seems that i have issue getting empty packets from osx into docker. 1 byte packets make it thru, but 0 len packets aren't getting through :|. yarg!

Are you sure it's OS X -> docker (not docker -> OS X) ? There was an old bug with kevent in OS X where zero length UDP packets would not be delivered.

It might also be worth forcing libuv to not use kevent and see if the problem persists.

**Comment by cdaringe** [comment]
within the container (alpine, luv), both read/write processes work well with the empty packet. only from external of the container (osx->alpine_container) can the empty packet not make it in. i _think_ that implicates osx? i concede, i have newb systems-fu. i went to try forcing a uring backend, but alpine doesn't have the right stuff.

update: i ran the container on a linux native box using `--net=host` to eliminate osx from the equation, and it worked.

😓 

thx for the tips! disturbing stuff 😆

**Comment by avsm** [comment]
If this is going through Docker for Mac, it may be an issue in vpnkit as it works with everything but 0 length packets and also passes through with net=host  /cc @djs55
