### ISSUE TITLE
Flows should be STREAM only

### ISSUE THREAD

**Issue by haesbaert** [ocaml-multicore/eio#367]
We need a different abstraction for DATAGRAM things that are not UDP sockets, this is the case for example for a file descriptor from socketpair(2) with SOCK_DGRAM, as well as some device specific things like bpf(4), tun(4), tap(4) and the likes.

This would help fixing issues #345 and #342.

This came up on a discussion where `Flow.write` with many buffers (over iovec limit) should be able to do multiple calls for a STREAM socket, but should error out for a DATAGRAM socket. Instead of us trying to shove both semantics in `Flow`, it's probably easier to split it into something else.

Ideally we could export a `write`/`read`/`close` which would be available for any kind of descriptor, then the udp_socket could add `recvfrom` and `sendto`, this way `Flow` can assume STREAM semantics while we deal with the rest elsewhere.

**Comment by talex5** [comment]
I think this is mostly fixed now. We have a separate `datagram_socket` type: https://github.com/ocaml-multicore/eio/blob/bd77643795898753b1d0823ba04a5a6fa901338d/lib_eio/net.mli#L114-L118

There's also the unified `Eio_unix.Fd.t` type for more low-level things. Possibly we should add read and write effects for those.

**Comment by talex5** [comment]
Closing, as flows are stream only and datagram sockets now have their own API.
