### ISSUE TITLE
`Buf_read.seq` return 'a Seq.t parser, but Seq.t is a delayed list

### ISSUE THREAD

**Issue by RCmerci** [ocaml-multicore/eio#380]
I used `Buf_read.seq` to construct a parser, like this:
```
let x =
  Eio_main.run @@ fun env ->
  let ( / ) = Path.( / ) in
  Path.with_open_in (Stdenv.cwd env / "filename.txt") @@ fun flow ->
  let buf = of_flow ~max_size:200 flow in
  Buf_read.lines buf
in 
List.of_seq x (* runtime error here: Exception: Stdlib.Effect.Unhandled(Eio_luv.Enter(_)) *)
```
This is the result of a delay computation.
I wonder if seq should just return 'a List.t parser?

**Comment by talex5** [comment]
This is intentional. You might not want to read all the lines, and if you do, you might not want to load them all into memory at the same time. You can just do the `List.of_seq` while the file is still open if you want to read everything. e.g.

```ocaml
Path.with_lines (Eio.Stdenv.cwd env / "filename.txt") List.of_seq
```
