### ISSUE TITLE
Eio.Semaphore.t hangs on n = 0

### ISSUE THREAD

**Issue by bikallem** [ocaml-multicore/eio#415]
Consider `Eio.Semaphore.t` usage below:

```ocaml
utop # Eio_main.run @@ fun env ->
let m = Eio.Semaphore.make 0 in
Eio.Semaphore.acquire m;;
...
```
The `...` part denotes  `Eio.Semaphore.acquire m` never returning, i.e. the program hangs. Should `Eio.Semaphore.make n` require `n > 0`? Is this a bug?

**Comment by talex5** [comment]
This is correct behaviour. It's waiting until another thread adds a resource by calling `release`. The stdlib behaves the same way:
```ocaml
utop # let m = Semaphore.Counting.make 0 in
Semaphore.Counting.acquire m;;
...
```

(well, except you can't cancel the stdlib version with Ctrl-C!)
