### ISSUE TITLE
Document that `secure_random` isn't quite a `Flow.source`

### ISSUE THREAD

**Issue by patricoferris** [ocaml-multicore/eio#422]
I accidentally tried to use `secure_random` as a `Flow.source` with `Flow.copy` which of course in retrospect is silly because there's no `End_of_file` to raise and the program just hangs. Maybe others might accidentally do the same and get confused, the best thing I think is maybe to add some documentation to stdenv ?

https://github.com/ocaml-multicore/eio/blob/80f5352526b260e9c32d7110844c7e7408e905f4/lib_eio/eio.mli#L246-L247

**Comment by talex5** [comment]
There's nothing wrong with using `Flow.copy` with an infinite source. It will run forever, but that might be what you want. It's essentially the same as doing `cat /dev/urandom | ...`

**Comment by patricoferris** [comment]
Good point! Perhaps just `is an infinite source of random bytes...` ?
