### ISSUE TITLE
eio_luv: reading a stream after closing it crashes the event loop

### ISSUE THREAD

**Issue by talex5** [ocaml-multicore/eio#424]
Seen in https://github.com/mirage/ocaml-cohttp/issues/965:

```
Uncaught exception in run loop:
Exception: Invalid_argument("read_start: handle used after calling close!")
Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
Called from Eio_luv.Low_level.Stream.read_into.(fun) in file "vendor/eio/lib_eio_luv/eio_luv.ml", line 512, characters 32-62
```

We should just discontinue the fiber with the exception, not kill the whole loop.

/cc @bikallem

**Comment by bikallem** [comment]
@talex5 do you mean here? 

https://github.com/ocaml-multicore/eio/blob/a36443f48a2f155811ceacf6c46694d1ca49240a/lib_eio_luv/eio_luv.ml#L377

It seems to be used in a few other places, i.e. getting the handle. It it okay if we discontinue in other use cases too?

**Comment by talex5** [comment]
Yes, but it's not worth spending a lot of time improving eio_luv, since we're planning to replace it anyway.
