### ISSUE TITLE
Eio.Flow.copy is very slow on mac OS

### ISSUE THREAD

**Issue by jinwoo** [ocaml-multicore/eio#453]
I ran one of the examples from the README file on my macbook.

```ocaml
let () =
  Eio_main.run @@ fun env ->
  Eio.Flow.copy
    (Eio.Stdenv.stdin env)
    (Eio.Stdenv.stdout env)
```

Compiling and running this code took ~38 sec against a 10G file while the standard library version only took ~2 sec.

Is this a limitation of the `eio_luv` backend?

**Comment by talex5** [comment]
Could you try it with the posix backend (#448) and see if that helps?

**Comment by patricoferris** [comment]
Took this for a spin on my mac (M1) and indeed see a noticeable improvement using the posix backend over libuv.

With `Eio_luv`:

```
truncate -s 2G dummy
_build/default/main.exe <dummy | pv >/dev/null
2.00GiB 0:00:13 [ 148MiB/s]
```

And then with `Eio_posix`:

```
truncate -s 2G dummy
_build/default/main.exe <dummy | pv >/dev/null
2.00GiB 0:00:03 [ 569MiB/s]
```

Whilst having a look I noticed the README still talks about this benchmark in terms of Eio_linux's use of `splice` but iiuc as of https://github.com/ocaml-multicore/eio/pull/327 this is not the case, perhaps we should comment that out for now?

**Comment by talex5** [comment]
Yeah, we should probably replace that section with a graph from https://github.com/ocaml-multicore/retro-httpaf-bench (there are some updates on my https://github.com/talex5/retro-httpaf-bench/tree/eio branch that need merging first though).

**Comment by talex5** [comment]
With Eio 0.9, macOS will be using the eio_posix backend now and the problem should be fixed.
