### ISSUE TITLE
(docs) writing stubs

### ISSUE THREAD

**Issue by ShawnROGrady** [ocaml-multicore/eio#483]
When writing stubs for an external library which performs blocking IO, is there any way to make the stubs useable in eio besides ‘Eio_unix.run_in_systhread’? If so, having some equivalent of [Lwt’s “writing stubs using Lwt”](https://ocsigen.org/lwt/latest/manual/manual) would be helpful.

**Comment by talex5** [comment]
`run_in_systhread` is what you need, yes (we don't yet have a version using thread pools, so it might be a little slower, too).

If you want to handle things yourself, you can look at the short implementation of `run_in_systhread`:

https://github.com/ocaml-multicore/eio/blob/39179a2f4e77b4e127ba6a43a250d85093aa9ef8/lib_eio/unix/eio_unix.ml#L40-L48

The basic steps are:
1. Suspend the calling fiber, getting an `enqueue` function.
2. Arrange for the function to get called when the operation is done (possibly from another thread).

It's also a good idea to check for cancellation at the start (as the code above does), and, if the operation can be cancelled after starting, register a function to call when Eio wants to cancel it (`Fiber_context.set_cancel_fn`).

**Comment by ShawnROGrady** [comment]
Excellent, thank you!
