### ISSUE TITLE
'Eio.Stream.add' dead locked when stream is empty and another domain is blocked taking

### ISSUE THREAD

**Issue by zenfey** [ocaml-multicore/eio#488]
Hi, as doc said Eio.Stream.t is thread safe between domains, I tried a simple 'add and take' example as below and add seems dead locked when take domain was firstly spawned. Did I use Eio.stream correctly or it's kind of issue?

```
open Eio.Std

let add stream =
  traceln "Adding %d ..." 0;
  Eio.Stream.add stream 0;
  traceln "Added %d ..." 0

let take stream =
  traceln "taking from stream ...";
  let x = Eio.Stream.take stream in
  traceln "Got %d" x

let () =
  let stream = Eio.Stream.create 5 in
  let dt = Domain.spawn (fun() -> take stream) in
  Unix.sleep 1;
  let da = Domain.spawn (fun() -> add stream) in
  Domain.join da;
  Domain.join dt
```

**Comment by talex5** [comment]
You need to run the Eio main loop (and use the domain manager to spawn domains).

What's happening here is that `dt` crashes with an unhandled effect exception, leaving the stream mutex locked.
Then `da` hangs trying to get the lock. Since you join on `da` first, you don't see the error. Try this:

```ocaml
open Eio.Std

let add stream =
  traceln "Adding %d ..." 0;
  Eio.Stream.add stream 0;
  traceln "Added %d ..." 0

let take stream =
  traceln "taking from stream ...";
  let x = Eio.Stream.take stream in
  traceln "Got %d" x

let () =
  Eio_main.run @@ fun env ->
  let run_in_domain = Eio.Domain_manager.run env#domain_mgr in
  let stream = Eio.Stream.create 5 in
  Fiber.both
    (fun () -> run_in_domain (fun() -> take stream))
    (fun () ->
       Unix.sleep 1;
       run_in_domain (fun() -> add stream)
    )
```

**Comment by patricoferris** [comment]
So I think the problem here is that in the `dt` domain, there is no handler installed (i.e. no `Eio_main.run`). This means the `Eio.Stream.take` is suspending and therefore performing an effect which goes unhandled so the domain is now ready to raise an exception the next time it gets joined. We then move on to `da` where we try to add to the stream. The stream implementation uses a Mutex to synchronise access, because of the unhandled effect in `dt` this mutex has not been released and so now `add` is deadlocked on that and then the whole program gets deadlocked with the called to `Domain.join da` (arguably we should catch the unhandled effect exception in https://github.com/ocaml-multicore/eio/blob/9656b89ffac71851cd7ea287bd2ed2011bbfbc05/lib_eio/stream.ml#L72 and release the mutex maybe). However, you should install the main handler and use the built-in Eio domain functions and then you should be good to go. We can mimic the spawn-join with fork-promise.

```ocaml
open Eio.Std

let add stream =
  traceln "Adding %d ..." 0;
  Eio.Stream.add stream 0;
  traceln "Added %d ..." 0

let take stream =
  traceln "taking from stream ...";
  let x = Eio.Stream.take stream in
  traceln "Got %d" x

let spawn ~sw mgr fn =
  Fiber.fork_promise ~sw (fun () -> Eio.Domain_manager.run mgr fn)

let () =
  Eio_main.run @@ fun env ->
  let mgr = Eio.Stdenv.domain_mgr env in
  Switch.run @@ fun sw ->
  let stream = Eio.Stream.create 0 in
  let dt = spawn ~sw mgr (fun() -> take stream) in
  Unix.sleep 1;
  let da = spawn ~sw mgr (fun() -> add stream) in
  Promise.await_exn da;
  Promise.await_exn dt
```

**Comment by patricoferris** [comment]
Haha, sorry! Should have taken a mutex on this issue ^^"

**Comment by zenfey** [comment]
> You need to run the Eio main loop (and use the domain manager to spawn domains).
> 
> What's happening here is that `dt` crashes with an unhandled effect exception, leaving the stream mutex locked. Then `da` hangs trying to get the lock. Since you join on `da` first, you don't see the error. Try this:
> 
> ```ocaml
> open Eio.Std
> 
> let add stream =
>   traceln "Adding %d ..." 0;
>   Eio.Stream.add stream 0;
>   traceln "Added %d ..." 0
> 
> let take stream =
>   traceln "taking from stream ...";
>   let x = Eio.Stream.take stream in
>   traceln "Got %d" x
> 
> let () =
>   Eio_main.run @@ fun env ->
>   let run_in_domain = Eio.Domain_manager.run env#domain_mgr in
>   let stream = Eio.Stream.create 5 in
>   Fiber.both
>     (fun () -> run_in_domain (fun() -> take stream))
>     (fun () ->
>        Unix.sleep 1;
>        run_in_domain (fun() -> add stream)
>     )
> ```

I see domain usage shall follow doc example either. It seems to me that in eio domains also become some io resource introduced in via the env argument. Thanks : )

**Comment by zenfey** [comment]
`kcas` sounds like provide a flexible and free way. deserves further look in. Thanks : )

> BTW, that program would work with ([upcoming WIP version of](https://github.com/ocaml-multicore/kcas/pull/32)) `kcas_data` that provides Eio style communication and synchronization primitives built using (upcoming WIP version of) `kcas` that provides blocking support:
> 
> 
> The goal is that the blocking mechanism in (upcoming WIP version of) `kcas` automatically _just works_ ™ with any scheduler (Eio or otherwise) that implements a simple asynchronous [trigger](https://github.com/ocaml-multicore/kcas/blob/add-blocking/src/trigger.mli) mechanism and provides it via DLS. Moreover the blocking mechanism even works across schedulers (i.e. when the two domains involved are running different schedulers).
