### ISSUE TITLE
enhancement: Implicit `clock` interface

### ISSUE THREAD

**Issue by Nymphium** [ocaml-multicore/eio#506]
The function interfaces of the current Time require a clock, so we need to propagate the clock object from the eio main handler to the deeper call sites.

One opinion is to fetch `clock` by `perform`ing effect such as:

```ocaml
(* in Time module *)
type _ Effect.t += Get : #clock Effect.t
let now' () = now @@ Effect.perform Get

...

let measure f =
  let t1 = Eio.Time.now' () in
  f ();
  let t2 = Eio.Time.now' () in
  t2 -. t1

...

Eio_main.run @@ fun env ->
Eio.Time.run env#clock @@ fun () ->
measure (fun () -> print_endline "hello")
```

**Comment by talex5** [comment]
Yes, [Get_monotonic_clock](https://ocaml-multicore.github.io/eio/eio/Eio_unix/Private/index.html#extension-Get_monotonic_clock) works that way (used to implement `Eio_unix.sleep`).

**Comment by Nymphium** [comment]
Additionally, we can express it more commonly, such as `switch` passed to `Fiber` functions.

**Comment by talex5** [comment]
You can do that, but it removes the benefit of using switches, which is to make the lifetimes clear. Creating a switch at the top-level and using it implicitly everywhere means functions can leak resources easily (e.g. forgetting to close a file).

Anyway, Eio doesn't prevent you from doing that, but it also doesn't want to encourage it.
