### ISSUE TITLE
Add task/worker pool similar to Domainslib task pool

### ISSUE THREAD

**Issue by darrenldl** [ocaml-multicore/eio#512]
Thanks for your work first of all, it's been nice to use.

The Domainslib integration as described in README works fine, but working with mutexes then becomes a bit complicated.

- Invoking `Eio.Mutex.lock` etc within a Domainslib (or just non-Eio I guess) domain causes it to stop progressing
  - Not unexpected, but was not straightforward to track down, and Eio data structure documentation doesn't seem warn about this
- Swapping to stdlib's `Mutex` works, but then suffers from the problem of locking the entire domain needlessly if used on the Eio side

Right now it seems that there are enough components to replicate task pool
- Run a few background workers upon pool construction using Fiber.fork and Domain_manager.run
- Construct promises, embed within a closure and pass it onto work stream `(unit -> unit) Eio.Stream.t` (same as domainslib example in readme)

And it would be very nice to be able to stay in Eio domains for parallel worker pools.

I'm happy to draft a PR in next few days if the addition is not deemed problematic.

**Comment by Sudha247** [comment]
Hi @darrenldl, thanks for bringing this up. Would [domain-local-await](https://github.com/ocaml-multicore/domain-local-await) work for you, for domainslib integration?

**Comment by darrenldl** [comment]
Thanks @Sudha247 @talex5 !

> We have an item in the 1.0 roadmap for this (which I've now linked to this issue).

Ah I must have missed it, oops, my bad.

> We might want to make an Eio.Pool abstraction first, and then build worker pools on top of that, but we can prototype one that starts all domains immediately without that.

Could you elaborate on that? I'm confused by what `Eio.Pool` should do by itself - is it a pool of fibers?

**Comment by talex5** [comment]
`Eio.Pool` would be similar to [Lwt_pool](http://ocsigen.org/lwt/5.5.0/api/Lwt_pool) - a generic way to hold resources, creating them as needed (up to a limit). But we can add that later.

**Comment by darrenldl** [comment]
I see, seems like a good skeleton to base the problem on indeed.

**Comment by patricoferris** [comment]
> Eio.Pool would be similar to [Lwt_pool](http://ocsigen.org/lwt/5.5.0/api/Lwt_pool) - a generic way to hold resources, creating them as needed (up to a limit). But we can add that later.

I think we can do a nicer implementation with the low-level primitives in Eio, but I did hastily port this whilst porting Irmin in case it is useful https://github.com/patricoferris/irmin/blob/direct-style/src/irmin-fs/unix/eio_pool.ml

**Comment by darrenldl** [comment]
Ooo neat! Will take a closer look when I actually begin the PR (if no one has beaten me to it by then).

At first glance it seems that `acquire` has a time-of-check time-of-use race condition if environment is parallel.

**Comment by polytypic** [comment]
Related to making synchronization primitives work across schedulers, you might be interested in this [example of how one might setup interop between Eio and Domainslib](https://discuss.ocaml.org/t/interaction-between-eio-and-domainslib-unhandled-exceptions/11971/10?u=polytypic) using the [kcas](https://github.com/ocaml-multicore/kcas/#readme) library (that uses the [domain-local-await](https://github.com/ocaml-multicore/domain-local-await/#readme) mentioned previously).

**Comment by talex5** [comment]
Added by #639.
