### ISSUE TITLE
expose current Eio backend in use as a string variable

### ISSUE THREAD

**Issue by avsm** [ocaml-multicore/eio#545]
It's currently not possible to log which Eio backend is in use, and we should expose a way to do this (potentially from Eio_main, but elsewhere is fine too).

Reported by @quernd

**Comment by talex5** [comment]
Yes, something like `backend_id : string` in [Stdenv.base](https://github.com/ocaml-multicore/eio/blob/a6c0be9affd1793613e5e23bba4258c9f56d2c36/lib_eio/unix/eio_unix.mli#L67) should do it.

**Comment by bord-o** [comment]
Hey this would be my first contribution, but I can take this on if that's ok. I already have a working version.

**Comment by talex5** [comment]
@bord-o: sounds good - feel free to open a PR!

**Comment by talex5** [comment]
Done in #560.
