### ISSUE TITLE
Benchmarks have stopped working

### ISSUE THREAD

**Issue by talex5** [ocaml-multicore/eio#565]
CI reports e.g.
```
dune exec -- ./bench/main.exe
Error: current-bench-data/duniverse/ocaml-iso639/dune-project: Permission
denied
make: *** [Makefile:7: bench] Error 1
```
(http://autumn.ocamllabs.io:8081/job/2023-06-23/103115-ocluster-build-a1126c)

/cc @Sudha247

**Comment by Sudha247** [comment]
I noticed this just now too. Looks like a configuration issue. The same error shows up on lockfree as well - http://autumn.ocamllabs.io:8081/job/2023-06-22/142045-ocluster-build-f9e018. (ping @punchagan @ElectreAAS)

**Comment by punchagan** [comment]
Yes, I've noticed this too. Thanks for the ping. I'll look into this first thing on Monday. Sorry for the inconvenience.

**Comment by talex5** [comment]
Thanks - will be useful to have benchmarks working again to see the effect of the changes in https://github.com/ocaml-multicore/eio/pull/567.

**Comment by punchagan** [comment]
The benchmarks are running again now. But looks like the PR #567 was merged before the benchmark run finished, and by default `current-bench` doesn't run benchmarks for closed/merged pull requests. The benchmark results for the merged commit are available here: https://autumn.ocamllabs.io/ocaml-multicore/eio/branch/main?worker=fermat&image=ocaml%2Fopam%3Adebian-ocaml-5.0

**Comment by talex5** [comment]
Thanks @punchagan - that's very useful!
