### ISSUE TITLE
current_bench not building Eio benchmarks anymore

### ISSUE THREAD

**Issue by avsm** [ocaml-multicore/eio#576]
Since #542 was merged, the current_bench fails to build the repository due to:

```
#10 4.833 eio_linux is now pinned to file:///home/opam/bench-dir (version dev)
#10 4.849 eio_main is now pinned to file:///home/opam/bench-dir (version dev)
#10 4.867 eio_posix is now pinned to file:///home/opam/bench-dir (version dev)
#10 4.869 eio_windows is now pinned to file:///home/opam/bench-dir (version dev)
#10 6.769 [eio.dev] synchronised (no changes)
#10 6.780 [eio_linux.dev] synchronised (no changes)
#10 6.789 [eio_main.dev] synchronised (no changes)
#10 6.858 [eio_posix.dev] synchronised (no changes)
#10 6.869 [eio_windows.dev] synchronised (no changes)
#10 9.819 [ERROR] eio_windows = dev unmet availability conditions: 'os-family = "windows"'
```

See http://autumn.ocamllabs.io:8081/job/2023-07-07/183839-ocluster-build-1e12ab

/cc @Sudha247

**Comment by talex5** [comment]
Yeah, that got merged a bit too soon!

> This will need an update to ocaml-ci so that it doesn't try testing Windows packages on Linux.

I might revert it to get the CI working again, and then update the solver later (I'm in the middle of porting the solver to Eio, so it's not a good time to be adding a new feature).

**Comment by talex5** [comment]
It's working again now.
