### ISSUE TITLE
Path.split does not work with backslash-encoded paths.

### ISSUE THREAD

**Issue by kentookura** [ocaml-multicore/eio#746]
If basename contains backslashes, it will return the string unmodified:
https://github.com/ocaml-multicore/eio/blob/37840760b1b99fd9f59f0dbced315c72f08e639d/lib_eio/path.ml#L52-L65

**Comment by talex5** [comment]
Backslashes are just normal filename characters for an `Eio.Path`:

https://github.com/ocaml-multicore/eio/blob/37840760b1b99fd9f59f0dbced315c72f08e639d/lib_eio/path.mli#L27-L28
