### ISSUE TITLE
ENOMEM with readme example

### ISSUE THREAD

**Issue by Cjen1** [ocaml-multicore/eio#80]
Hi! This project looks excellent!

I was trying out the example in the README:
```
#require "eio_main";;
open Eio.Std;;

let main ~stdout = Eio.Flow.copy_string "hello World" stdout
Eio_main.run @@ fun env -> main ~stdout:(Eio.Stdenv.stdout env)
;;
```

This is failing with `Unix.Unix_error(Unix.ENOMEM, "io_uring_register_buffers", "")`.

There is sufficient free RAM available, so I expect that this is due to some system limit but have no idea how to debug it and can't find any documentation on this error either.

**Comment by talex5** [comment]
Perhaps you're running in a Docker container? Try e.g. `docker run --ulimit memlock=819200000:819200000 ...` if so. If not, try `ulimit -l`.

**Comment by Cjen1** [comment]
I'm running this within Nixos, which is probably the cause.

`ulimit -l` returns `64`

So I presume that that is way too low :)

**Comment by talex5** [comment]
Yes, that will be the problem! Maybe we should make the default a bit smaller, though.

**Comment by Cjen1** [comment]
Yep that works!
