### ISSUE TITLE
Is IO prioritisation possible?

### ISSUE THREAD

**Issue by Cjen1** [ocaml-multicore/eio#81]
This may be a bit of a weird request, but I've been working on some consensus systems recently, and being able to prioritise internal communications over external ones is quite important

Specifically there for these systems you have multiple nodes communicating with each other (keepalives etc), and also taking client requests. The problem is if there are too many client requests, and no prioritization, the internal communication can end up being delayed waiting for a batch of client requests to be handled. This results in other nodes believing that the leader is dead and hence calling an election.

The way I've fixed this previously was to separate the scheduling spaces (ensuring fairness) via either processes or system threads, one for internal communication and one for external.

One hope I had with effects is that it may be possible to do this prioritisation by using an effect handler to intercept the IO effects, and then assign them to the correct priority level.

This could look something like the following
```
let client_rpc_handler = ...
let internal_rpc_handler = ...

let intercept f ~priority =
  match f () with
  | x -> x
  | Effect e -> perform_with_priority e ~priority

let main () =
  intercept ~priority:2 client_rpc_handler;
  intercept ~priority:1 internal_rpc_handler;
  ()
```
And would optimally have the effect of if there are packets waiting on the client sockets and the internal sockets, that it would read from the internal sockets first (generalised over all IO operations).

I understand that this may be impossible to do, but it would be much simpler to do this in the concurrency scheduler. Additionally I'm also not sure whether this is a wrong-headed approach and that another solution would work better.

**Comment by talex5** [comment]
Yes, using a separate multicore domain would work for this. However, Eio is currently lacking primitives for communicating easily between domains.

With the io-uring backend, there is an `ioprio` field that might be useful (I don't know - I've never used it). It's not exposed in the OCaml API at the moment, though. Apart from that, Linux will do the reads in whatever order it wants.

The easiest way is probably to have each reader (handling one client connection) push the client request onto an `Eio.Stream` and have a single fibre pulling the requests off and handling them, doing `Fibre.yield` after each request. Then when a high-priority internal message arrives, that doesn't go on the queue and is instead handled immediately. But that assumes that it's the processing of the requests that is slow, rather than merely receiving them.

**Comment by Cjen1** [comment]
The stream approach should work I think (given limited size streams), but would require that any rpc library to implement that kind of processing.

Is there any way to do prioritisation of the scheduling of fibres themselves?

**Comment by talex5** [comment]
Is this still a problem?

> being able to prioritise internal communications over external ones is quite important

I think we always prioritise internal comms over IO now. Both uring and luv backends keep a special "IO" task in the run queue to remind them to check for IO from time to time because otherwise doing `Fiber.yield` in a loop would block everything else.

**Comment by Cjen1** [comment]
After rewriting the IO layer, this is no longer an issue for me specifically.

What was occurring was that if client requests were coming in they would each start a new fiber waiting for the resolution of that rpc request.
The issue was that if client requests kept coming in the time between main loop runs would increase, effectively causing queuing at the client side.

I've now redone the IO layer such that it is one fiber per client which should prevent this from occurring and also I can chuck it into another domain to avoid this entirely.

I think that if there was some overarching scheduling prioritisation feature this would help (attaching each fiber some priority) but I also fully understand how much work that would entail and also that it would be difficult to avoid starvation etc.
Additionally if other solutions exist (such as popping the client communication into its own domain) then this should be a non-issue for now.
