### ISSUE TITLE
Any plans on supporting js_of_ocaml?

### ISSUE THREAD

**Issue by Lupus** [ocaml-multicore/eio#85]
Is eio library supposed to be bound to OCaml native applications only? Let's assume that JSOO gets support for effects [1] - will it be possible to have eio compile to JS backend? For context - we have some proprietary project that is based on Lwt and relies on the fact that Lwt can be ran both on native and in JS. For JS we use node.js as target platform. Thinking about possible migration path for OCaml 5.

[1] https://discuss.ocaml.org/t/ocaml-multicore-effects-and-js-of-ocaml/8502

**Comment by talex5** [comment]
The long-term goal is for it to work everywhere, including in the browser and in unikernels. At the moment, there are still some remaining uses of the Unix module (e.g. `Unix.inet_addr`) in `eio.mli` though.

**Comment by talex5** [comment]
See https://github.com/ocaml-multicore/eio/pull/405
